### ISSUE TITLE
Subtitle styling

### ISSUE THREAD

**Issue by willmtemple** [streamaserver/streama#612]
The default style for HTML5 subtitle tracks is designed to look like closed-captions on television, but users who are familiar with VLC or MPV and not with closed captioning will probably prefer the nicer styles of those players. I would think that it should be configurable, since some users will require captions rather than just subtitles and might prefer the caption style.

@dularion mentioned in #152 that she plans to move away from HTML5 subtitles/captions, but it might be easier to let HTML5 handle the subs and let the server work out how to extract embedded subtitles and convert ASS and other formats to VTT. You can [add the styles directly to the converted VTT](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API) or put them in the page CSS. Is there a reason to render subtitles manually that I haven't thought of?

I whipped up some real quick CSS in dev tools that changes how the `::cue` pseudoelement looks:

```css
::cue {
    color: white;
    background: transparent;
    font-weight: 700;
    font-size: 48pt;
    text-shadow: 4px 4px 0 #000, -2px -2px 0 #000, 2px -2px 0 #000, -2px 2px 0 #000, 2px 2px 0 #000;
}
```
The biggest differences are that the subtitles are much larger, bolder, and only outlined, rather than completely filled in black. I only tested it in Chrome on a large monitor.

changes this:
![closed_caption](https://i.imgur.com/DrTS4bX.png)

to this:
![mpv_like](https://i.imgur.com/oNbKY7W.png)
