### ISSUE TITLE
Movie not playing

### ISSUE THREAD

**Issue by kerberjg** [streamaserver/streama#718]
### Issue description

After attempting to upload and play a movie (not happening with TV series), the movie does not play, displaying a "Internal Server Error" message in a red popup.

Inspecting the HTTP request reveals that the failing request is made to the URL`/video/show.json?id=1`. Interestingly enough, requests to `/movie/show.json?id=1` are evaluated correctly (only on other pages, it does not happen in the player). Stack trace is at the end of this report.

When assigning the same file to a TV series episode, the file is played correctly, and requests to `/video/show.json?id=3` do not fail.

---

Sometimes the connection to the DB times out as well, with the following message in MariaDB:

```
[Warning] Aborted connection 34 to db: 'streama' user: 'streama' host: '172.19.0.4' (Got timeout reading communication packets)
```

The result of that is the whole application responding with `{"message":"Internal server error","error":500}` to ANY HTTP request, causing the web interface to not show anymore either. I forgot to save the stack trace of that, however I remember seeing: `com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 636,743 milliseconds ago.  The last packet sent successfully to the server was 636,743 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.`

### Steps to Reproduce

1. Create a movie
2. Upload a file for the movie
3. Attempt to play the movie

### Expected Behaviour

Movie playing (without any other unexpected behavior)

### Actual Behaviour

Movie does not play; sometimes DB connection times out, doesn't reconnect, causing the whole server to respond with 500 to anything.

### Environment Information

- **Operating System**: Docker container of 'gkiko/streama' (Linux container, host OS irrelevant)
- **Streama version**: v1.6.0-FINAL
- **DB**: MariaDB 10.3.12

Here's the docker-compose.yml used:

```
version: '2'

services:
    streama:
        image: 'gkiko/streama:v1.6.0-FINAL'
        working_dir: '/app'
        entrypoint: 'java'
        command: ["-Dgrails.env=mysql", "-jar", "streama.war"]
        hostname: streama
        ports:
            - 8080:8080
        environment:
            - ACTIVE_PROFILE=mysql
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=streama
            - MYSQL_USER=streama
            - MYSQL_PASSWORD=streama_password
        restart: always
        volumes:
            - ./data:/data/streama
        links:
            - mysql
        depends_on:
            - mysql
    mysql:
        image: 'mariadb:10'
        hostname: mysql
        restart: always
        volumes:
            - ./mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=streama
            - MYSQL_USER=streama
            - MYSQL_PASSWORD=streama_password
        expose:
            - 3306
```

### Stack trace

https://pastebin.com/3Jj5mk84
