### ISSUE TITLE
Bug related to Season "Unknown" (or Season 0)

### ISSUE THREAD

**Issue by IngwiePhoenix** [streamaserver/streama#786]
### Issue description
I wanted to add a local copy of the "Akame Ga Kill!" anime to my Streama instance and have uploaded it to the server with a file format that should match: "Akame Ga Kill! SxxExx.mp4".

However, [IMdb](https://www.imdb.com/title/tt3742982/episodes?season=1) reports two seasons:

* Unknown
* 1

In Streama, this is represented as season 0 and 1. So, my original understanding was:

* Season Unknown -> Season 0
* Season 1 -> Season 1

This is actually reflected this very way within Streama's view. However, running a matcher on a file ending with `S01E01" (which should be Season 1, Episode 1) tells me that the episode is already available and points me at Season **0**! Since I uploaded Season 0 manually by assigning the files by hand instead of using the automation, it is indeed filled. But now, I want to bulk-add Season 1, which seems to be impossible.

My guess: Because season 0 in Streama is season "unknown" in IMdb, we might see a scenario where the unknown season receives the index 0, and season 1 is supposed to have index 1, but since arrays start at 0, it is instead inserted there.

Or in other words: season "unknown" is mistreated completely.

### Steps to Reproduce

1. Create the "Akame Ga Kill!" TV Show on your Streama instance.
2. Upload a file named `Akame Ga Kill! S01E01.mp4`
3. Select the Bulk-creation tool, select the file from above, and watch.

Since you may not have season 0 filled in, it should report the match as being found...and it will try to assign `S01E01` to what SHOULD be `S00E01`.

### Expected Behaviour
I expected that a file named `S01E01` is added to the actual season 1, not season 0 - and in turn, that a file named `S00E01` is added to the unknown season, ergo season 0.

### Actual Behaviour
A message that kindly tells me that the episode is already assigned, although it definitively is not - at least it shouldn't be.

### Environment Information

- **Operating System**: 
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- **Streama version**: Latest
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: Not customized - my Java-fu isn't good enough for this :)
- **Container Version (If Applicable):** None - bare metal installation.

**Comment by IngwiePhoenix** [comment]
In addition:

```yml
environments:
    production:
        dataSource:
            #Default embedded database
            driverClassName:  'org.h2.Driver'
            url: jdbc:h2:./streama;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: root
            password:
            
            #For mysql database
            #driverClassName:  'com.mysql.jdbc.Driver'
            #url: jdbc:mysql://localhost/streama
            #username: root
            #password:
        server:
            port: 8881

streama:
  regex:
    movies: ^movie\.(?<Name>.*)[._ ]\(\d{4}\).*
    shows:
      - ^(?<Name>.+)[._ ]S(?<Season>\d{2})E(?<Episode>\d{2,3}).*
      - ^(?<Name>.+)[._ ](?<Season>\d{1,2})x(?<Episode>\d{2,3}).*
```
